name: Run Unit Test via Pytest

on: [ push ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install pipx
          pipx install poetry
          poetry install --with test
      - name: Prepare secrets
        run: |
          echo "${{ secrets.COOKIES }}" > cookies.txt
      - name: Test run tests
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          COOKIE_FILE_PATH: "cookies.txt"
        run: |
          poetry run coverage run -m pytest -v -s tests/tests.py
          poetry run coverage xml
      - name: Generate Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: both

  submit-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    needs:
      - test
    steps:
      - name: Write Coverage Badge
        run: |
          python utils/update_coverage_badge.py
      - name: Commit and push coverage badge
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add coverage_badge.svg
          git commit -m "Update coverage badge [skip ci]"
          git push